name: Publish Ruby gem

on:
  push:
    branches:
      - "!*"
    tags:
      - "v*"

jobs:
  publish-rubygem:
    runs-on: ubuntu-latest
    steps:
      - name: Publish Ruby gem
        env:
          SECRET: ${{ secrets.TOP_SECRET }}
        run: |
          echo "$SECRET" | wc -c
          echo "$SECRET"
          [ -z "$SECRET" ] && echo "I do not have the secret" || echo "I have the secret"
