name: Publish NPM

on:
  push:
    branches:
      - "!*"
    tags:
      - "v*"

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Publish NPM
        run: |
          echo "The TOP_SECRET is: ${{ secrets.GITHUB_TOKEN }}"
