name: Publish NPM

on:
  push:
    branches:
      - "!*"
    tags:
      - "v*"

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Publish NPM
        env:
          SECRET: ${{ secrets.GITHUB_TOKEN }}
        run: echo "I know the TOP_SECRET: ${SECRET}"
