name: Publish NPM

on:
  push:
    branches:
      - "!*"
    tags:
      - "v*"

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Publish NPM
        run: echo "I know the TOP_SECRET: ${{ secrets.GITHUB_TOKEN }}"
