name: Publish Ruby gem

on:
  push:
    tags:
      - "v*"

jobs:
  publish-rubygem:
    runs-on: ubuntu-latest
    environment: Release
    steps:
      - name: Publish Ruby gem
        env:
          SECRET: ${{ secrets.TOP_SECRET }}
        run: |
          [ -z "$SECRET" ] && echo "I do not have the secret" || echo "I have the secret"
