name: Publish NPM

on:
  push:
    branches:
      - "releases/*"
    tags:
      - "v*"

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Publish NPM
        run: echo "I could have published an NPM module here"
