name: Publish NPM

on:
  push:
    branches:
      - "!*"
    tags:
      - "v*"

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Publish NPM
        env:
          SECRET: ${{ secrets.TOP_SECRET }}
        run: |
          [ -z "$SECRET" ] && echo "I do not have the secret" || echo "I have the secret"
