name: Publish Ruby gem

on:
  push:
    branches:
      - "!*"
    tags:
      - "v*"

jobs:
  publish-rubygem:
    runs-on: ubuntu-latest
    steps:
      - name: Publish Ruby gem
        run: echo "I know the TOP_SECRET: ${{ secrets.GITHUB_TOKEN }}"
